runtime: python
env: flex
entrypoint: daphne django_video.asgi:application --port $PORT --bind 0.0.0.0


runtime_config:
  python_version: 3

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1


# Update with Redis instance details
env_variables:
  REDISHOST: '10.25.45.251'
  REDISPORT: '6379'

# Update with Redis instance network name
network:
  name: default


